CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password_digest VARCHAR NOT NULL,
);

ALTER TABLE cases
ADD COLUMN user_id INTEGER REFERENCES users(id);